import sys
import shutil
import re
from pathlib import Path
from grpc_tools import protoc

def find_project_root(start_path: Path) -> Path: # required because im too lazy to readjust paths every major change
    root_markers = {"src", ".git"} # with the way we plan our directories, .env cannot be an anchor point
    current = start_path
    for _ in range(6): # 6 so it doesn't traverse the entire system
        if any((current / marker).exists() for marker in root_markers):
            return current
        if current.parent == current: break
        current = current.parent
    print("Error: Could not find project root.", file=sys.stderr)
    sys.exit(1)

SCRIPT_PATH = Path(__file__).resolve()
OUTPUT_DIR = SCRIPT_PATH.parent
PROJECT_ROOT = find_project_root(SCRIPT_PATH.parent)

REPO_ROOT = PROJECT_ROOT / "external" / "protobufs"
PROTO_SRC_DIR = REPO_ROOT / "csgo"
TEMP_BUILD_DIR = PROJECT_ROOT / "temp_proto_build"

FILES_TO_COMPILE = [
    "cstrike15_gcmessages.proto", # req
    "gcsdk_gcmessages.proto", # dep
    "engine_gcmessages.proto", # dep
    "steammessages.proto" # req
]

# rebuilding takes time, we check to make sure files are good to go before building
def needs_rebuild() -> bool:
    """Checks if source protos are newer than generated python files."""
    if not OUTPUT_DIR.exists():
        return True
    
    generated_files = list(OUTPUT_DIR.glob("*_pb2.py"))
    if not generated_files or len(generated_files) < len(FILES_TO_COMPILE):
        return True
        
    oldest_gen_time = min(f.stat().st_mtime for f in generated_files)
    
    for fname in FILES_TO_COMPILE:
        src = PROTO_SRC_DIR / fname
        if not src.exists(): continue
        if src.stat().st_mtime > oldest_gen_time:
            return True
            
    return False

"""
since we use SteamClient, it has many similarities to these protobufs.
we need to prepare the file so that protobufs can be referred to as 
valve_pbuf.CMsgClientHello and python doesn't get confused
"""
def prepare_file(src_path: Path, dest_path: Path):
    try:
        content = src_path.read_text(encoding='utf-8', errors='ignore')
        # Remove existing package
        content = re.sub(r'^package\s+[\w\.]+;', '', content, flags=re.MULTILINE)
        # Inject custom package
        new_content = f'package valve_pbuf;\n' + content
        # Strip leading dots from types to fix internal references
        new_content = re.sub(r'([ \(\)=])\.([A-Z])', r'\1\2', new_content)
        dest_path.write_text(new_content, encoding='utf-8')
    except Exception as e:
        print(f"Failed to prepare {src_path.name}: {e}", file=sys.stderr)
        sys.exit(1)

"""
fixes imports for the autogenerated scripts
"""
def fix_imports(output_dir: Path):
    for py_file in output_dir.glob("*_pb2.py"):
        content = py_file.read_text(encoding='utf-8')
        
        # Change "import x_pb2" to "from . import x_pb2"
        new_content = re.sub(
            r'^import (\w+_pb2) as', 
            r'from . import \1 as', 
            content, 
            flags=re.MULTILINE
        )
        
        if content != new_content:
            py_file.write_text(new_content, encoding='utf-8')

"""
force=True to build irregardless of how old protobufs are
"""
def build(force=False):
    if force or needs_rebuild():
        if not PROTO_SRC_DIR.exists():
            print(f"Error: Protobuf source not found at: {PROTO_SRC_DIR}", file=sys.stderr)
            sys.exit(1)

        if TEMP_BUILD_DIR.exists(): shutil.rmtree(TEMP_BUILD_DIR) # create temp dir
        TEMP_BUILD_DIR.mkdir(parents=True)
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        for fname in FILES_TO_COMPILE:
            prepare_file(PROTO_SRC_DIR / fname, TEMP_BUILD_DIR / fname)

        include_paths = [str(TEMP_BUILD_DIR), str(REPO_ROOT)]
        proto_files = [str(TEMP_BUILD_DIR / f) for f in FILES_TO_COMPILE]

        # checks grpc, temp directory repo root, and then place the files in cs2module
        command = [
            'grpc_tools.protoc',
            f'-I{include_paths[0]}',
            f'-I{include_paths[1]}',
            f'--python_out={str(OUTPUT_DIR)}',
        ] + proto_files

        exit_code = protoc.main(command)
        shutil.rmtree(TEMP_BUILD_DIR)

        if exit_code != 0:
            print("Error: Protobuf compilation failed.", file=sys.stderr)
            sys.exit(exit_code)

    fix_imports(OUTPUT_DIR) # we fix imports always as its cheap

if __name__ == "__main__":
    force_rebuild = "--force" in sys.argv
    build(force=force_rebuild)