# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        ref: ${{ github.head_ref }}
        
    - name: Install uv
      uses: astral-sh/setup-uv
      with:
        enable-cache: true
        cache-dependency-glob: "src/requirements.txt"
        
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        uv pip install --system ruff pytest
        if [ -f src/requirements.txt ]; then uv pip install --system -r src/requirements.txt ; fi

    
    - name: Lint and Format with Ruff # this currently does not catch the compiled pythons for protobufs
    # using exit-zero cause i want to see what happens when this completes
      run: |
        ruff format .
        ruff check --fix --exit-zero .

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: auto-format and lint fixes (ruff)"
        file_pattern: "*.py"

    - name: Test with pytest
      run: |
        pytest
